2025-01-16 13:47:03 UTC
Windows-10-10.0.19045
Ren'Py 8.2.3.24061702

Early init took 0.04s
Loading error handling took 0.02s

Full traceback:
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\main.py", line 455, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\script.py", line 359, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\script.py", line 957, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\script.py", line 590, in finish_load
    check_name(node)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\script.py", line 566, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('game/gui.rpy', 1732294974, 571) is defined twice, at game/gui.rpy:11 and game/images/code-tyan/code-tyan/game/gui.rpyc:11.

While loading the script.
ScriptError: Name ('game/gui.rpy', 1732294974, 571) is defined twice, at game/gui.rpy:11 and game/images/code-tyan/code-tyan/game/gui.rpyc:11.
