I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    with Dissolve(1.5)
OSError: Couldn't find file 'Till Death Do Us Part.ogg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    with Dissolve(1.5)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1363, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\exports.py", line 1782, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 1549, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2738, in interact_core
    renpy.audio.audio.interact()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\audio\audio.py", line 1245, in interact
    periodic()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\audio\audio.py", line 1199, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\audio\audio.py", line 1177, in periodic_thread_main
    periodic_pass()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\audio\audio.py", line 1119, in periodic_pass
    c.periodic()
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\audio\audio.py", line 528, in periodic
    topf = load(filename)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\loader.py", line 672, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'Till Death Do Us Part.ogg'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Fri Feb 21 18:26:42 2025
