I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 227, in script
    e_nvl m1"А ты не хочешь немного сухариков...?"
Exception: Say has image attributes ('m1',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 227, in script
    e_nvl m1"А ты не хочешь немного сухариков...?"
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\exports.py", line 1494, in say
    who(what, *args, **kwargs)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\character.py", line 1332, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\character.py", line 1151, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\Мария\Downloads\renpy-8.2.3-sdk\renpy\character.py", line 1077, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('m1',), but there's no image tag associated with the speaking character.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
code tyan 1.0
Sat Mar 29 21:31:13 2025
